name: Build and Release

on:
  push:
    tags:
      - '*' # Gatilho para qualquer tag sem prefixo específico

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Install Apache Ant
        run: sudo apt-get install ant

      - name: Build with Ant
        run: ant -f build.xml

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build/L2J_BrUnity_CT_2.6_HighFive.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/L2J_BrUnity_CT_2.6_HighFive.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

